Issues/22
marceldobrica/training pull request #35
Opened 2022-03-23 09:55 UTC by marceldobrica

2022-03-23 15:44 UTC, ovidiuenache commented on .env
> +PROGRAMME_MAX_TIME_MINUTES=360
@marceldobrica this PR holds the fixes from this PR: https://github.com/marceldobrica/training/pull/34

Please create specific and isolated PRs.

2022-03-23 15:44 UTC, ovidiuenache requested changes
Please address the feedback above

2022-03-24 07:53 UTC, ovidiuenache commented on .env
> +PROGRAMME_MAX_TIME_MINUTES=360
Pease rebase this one

2022-03-24 08:45 UTC, marceldobrica commented
git rebase main issues/22... next git pull ... and push

2022-03-24 09:14 UTC, merged